server:
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/workbench?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

sa-token:
  token-name: Authorization
  timeout: 86400
  active-timeout: 1800
  is-concurrent: true
  is-share: true
  token-style: uuid
  is-log: false
  is-read-header: true
  is-read-body: false
  is-read-cookie: false

feishu:
  app-id: cli_a9381579e779db
  app-secret: UqVn2bEkODjNiszvgg7QLDAG4MHffu
  base-url: https://open.feishu.cn

logging:
  level:
    com.xiaogui: debug
